### ISSUE TITLE
Need to deploy go lang function from zip file

### ISSUE THREAD

**Issue by sadanand25** [mthenw/serverless-go-plugin#22]
Hello,

I am trying to deploy a zip file , it contain go language function by using the serverless.yaml 

below is the file FYI.
Your help is highly appreciated..

functions:
  Lambda:
    handler: src/payshield/${self:provider.stage}/-events
    name: '${self:provider.stage}--events-lambda'
    description: '   add description'
    role: Role
    package:
      patterns:
        - '!*/**'
        - '!*'
        - 'src/xxasd/${self:provider.stage}/events.zip'
    memorySize: 128
    timeout: 15

**Comment by hexadecy** [comment]
To use a zip file in serverless you have to use the 
```
package:
  artifact: "src/xxasd/${self:provider.stage}/events.zip"
```
