### ISSUE TITLE
Support for Arm64 architecture with provided.al2 runtime

### ISSUE THREAD

**Issue by hexadecy** [mthenw/serverless-go-plugin#24]
I think the go1.x runtime shouldn't be used anymore as it runs on Amazon Linux 1 which is end-of-life.

Please merge #23 

There are lots of advantages to using the custom runtime:
- Support for arm64 and x86_64
- Support for Lambda Extensions
- Amazon Linux 2
- No RPC calls
- Smaller build and faster cold start

**Comment by mthenw** [comment]
Fixed by 2.1.0
