### ISSUE TITLE
Add ability to exclude functions (eg when using Container Images)

### ISSUE THREAD

**Issue by AnalogJ** [mthenw/serverless-go-plugin#54]
When a function `image` is provided, the go plugin should not attempt to compile code (as the handler key is missing).
https://www.serverless.com/blog/container-support-for-lambda

an Exclude key, similar to the newrelic plugin, would be ideal.

**Comment by OranShuster** [comment]
We have a mix of containerized and compiled go code. I don't see the plugin trying to compile our containerized functions
can you share a config of a function that is being compiled on deploy/package?

**Comment by mthenw** [comment]
Fixed with the above PR
