### ISSUE TITLE
Setting environment variables on windows fails

### ISSUE THREAD

**Issue by olafur-palsson** [mthenw/serverless-go-plugin#6]
`Go Plugin: Error compiling "backupConfluence" function (cwd: .): Command failed: GOOS=linux go build -ldflags="-s -w" -o .bin\backupConfluence main.go
'GOOS' is not recognized as an internal or external command,
operable program or batch file.`

This needs to be configured so that it uses the syntax of the current shell environment.

**Comment by mthenw** [comment]
Thanks for creating this issue! I will try to fix it today.

**Comment by mthenw** [comment]
Just released v1.6.0 with a fix. Please let me know if it works.
